spring:
  application:
    name: spring-ai-mini-project
  datasource:
    url: jdbc:postgresql://localhost:5432/vectordb
    username: postgres
    password: Pass@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5-coder:3b
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      pgvector:
        initialize-schema: true
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always


logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG
